#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Usage: $(basename "$0") <sourcefile>" >&2
  exit 1
fi

while read line; do
        firstWord="${line%% *}"
        if [[ "$firstWord" == "include" ]]; then
                restOfLine="${line#* }"
                cat "$restOfLine"
        else
                echo "$line"
        fi
done < $1
